version: "3"

services:
  datacube-manager:
    image: registry.dpi.inpe.br/brazildatacube/data-cube-manager:0.0.2
    ports:
      - "8080:8080"
    environment:
      - URL_CUBE_BUILDER=http://localhost:5000
      - ENVIRONMENT_VERSION=local